# Generated by Django 3.1.2 on 2020-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('images', models.ImageField(upload_to='images/')),
                ('link', models.URLField(blank=True)),
                ('trueReserch', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
