# Generated by Django 3.1.6 on 2021-06-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20201205_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymodel',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='activitymodel',
            name='genre',
            field=models.CharField(choices=[('secondary', 'Product'), ('info', 'Research'), ('light', 'Others')], default='Product', max_length=50),
        ),
    ]
